{
  description = "My NixOS Configuration with Marchyo";

  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";

    # Marchyo - Modern NixOS distribution
    marchyo = {
      url = "github:Jylhis/marchyo";
      inputs.nixpkgs.follows = "nixpkgs";
    };

    # Home Manager (brought in by Marchyo, but declared explicitly)
    home-manager = {
      url = "github:nix-community/home-manager";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs =
    {
      nixpkgs,
      marchyo,
      home-manager,
      ...
    }@inputs:
    {
      # Replace 'hostname' with your actual hostname
      nixosConfigurations.hostname = nixpkgs.lib.nixosSystem {
        system = "x86_64-linux";
        specialArgs = { inherit inputs; };

        modules = [
          # Hardware configuration (generated by nixos-generate-config)
          ./hardware-configuration.nix

          # Marchyo NixOS modules
          marchyo.nixosModules.default

          # Home Manager as NixOS module
          home-manager.nixosModules.home-manager

          # Your main configuration
          ./configuration.nix
        ];
      };

      # Optional: Standalone Home Manager configuration
      # homeConfigurations.username = home-manager.lib.homeManagerConfiguration {
      #   pkgs = nixpkgs.legacyPackages.x86_64-linux;
      #   modules = [
      #     marchyo.homeModules.default
      #     ./home.nix
      #   ];
      # };
    };
}
