export type Format = "text" | "json";

export type Runtime = {
  format: Format;
  noColor: boolean;
  forceColor: boolean;
  plain: boolean;
  noAnimation: boolean;
  noInput: boolean;
  quiet: boolean;
  verbose: number;
};

export type ColorMode = "auto" | "always" | "never";

export type RuntimeFlags = {
  format?: string;
  color?: string; // auto | always | never
  noColor?: boolean;
  plain?: boolean;
  noAnimation?: boolean;
  noInput?: boolean;
  quiet?: boolean;
  verbose?: number;
};

export const SUPPORTED_FORMATS: readonly Format[] = ["text", "json"] as const;

// Honors the canonical color-precedence chain (jylhis/design §2.5.1):
//   1. NO_COLOR env set                            -> off
//   2. --no-color flag or --color=never            -> off
//   3. CLICOLOR_FORCE env or --color=always        -> on
//   4. FORCE_COLOR env (non-zero/non-empty)        -> on
//   5. default: on iff isatty(stdout) && TERM != "dumb"
//
// `--plain` is a stronger separate switch (per §2.5.1): it implies noColor
// AND noAnimation AND swaps glyphs for word prefixes in output helpers.
export function buildRuntime(
  flags: RuntimeFlags = {},
  env: NodeJS.ProcessEnv = process.env,
  isTTY: boolean = Boolean(process.stdout.isTTY),
): Runtime {
  const format = parseFormat(flags.format);

  const colorMode: ColorMode =
    flags.color === "never" || flags.noColor === true
      ? "never"
      : flags.color === "always"
        ? "always"
        : "auto";

  const envNoColor = env.NO_COLOR !== undefined && env.NO_COLOR !== "";
  const envForceColor =
    (env.CLICOLOR_FORCE !== undefined && env.CLICOLOR_FORCE !== "0") ||
    (env.FORCE_COLOR !== undefined &&
      env.FORCE_COLOR !== "" &&
      env.FORCE_COLOR !== "0");
  const dumbTerm = env.TERM === "dumb";

  let noColor: boolean;
  let forceColor = false;
  if (envNoColor) noColor = true;
  else if (colorMode === "never") noColor = true;
  else if (colorMode === "always" || envForceColor) {
    noColor = false;
    forceColor = true;
  } else if (flags.plain === true) noColor = true;
  else if (dumbTerm) noColor = true;
  else noColor = !isTTY;

  const plain = flags.plain === true;

  // Animation always requires a real TTY; --color=always / FORCE_COLOR
  // affects color but not cursor-positioning capability.
  const noAnimation =
    flags.noAnimation === true || plain || dumbTerm || !isTTY;

  const noInput =
    flags.noInput === true || (env.CI !== undefined && env.CI !== "");

  // Apply the no-color decision globally so any library reading these env
  // vars (chalk/ink/etc.) sees the right state. Must happen before Ink mounts.
  if (noColor) env.NO_COLOR = "1";
  if (forceColor && !noColor) env.FORCE_COLOR = env.FORCE_COLOR ?? "1";

  // MARCHYO_DEBUG bumps verbose count by one; explicit -v flags still win.
  const envDebug =
    env.MARCHYO_DEBUG !== undefined && env.MARCHYO_DEBUG !== ""
      ? 1
      : 0;

  return {
    format,
    noColor,
    forceColor,
    plain,
    noAnimation,
    noInput,
    quiet: flags.quiet === true,
    verbose: Math.max(flags.verbose ?? 0, envDebug),
  };
}

function parseFormat(raw: string | undefined): Format {
  if (raw === undefined || raw === "") return "text";
  if ((SUPPORTED_FORMATS as readonly string[]).includes(raw)) return raw as Format;
  // Throw with a guideline-compliant usage error message that names the
  // supported subset rather than commander's autogenerated list.
  const supported = SUPPORTED_FORMATS.join(", ");
  throw new FormatError(
    `unsupported --format value: "${raw}"; supported: ${supported}`,
  );
}

export class FormatError extends Error {
  override name = "FormatError";
}
