pragma Singleton
import QtQuick

// Index of the shell plugins baked into this store shell (the build-time
// Option A model). packages/marchyo-shell/package.nix copies each declared
// plugin into share/marchyo/shell/plugins/<id>/ and regenerates the `plugins`
// list below with each manifest's id, kinds, and entry-point URLs. Nothing is
// discovered at runtime; there is no ~/.config plugin dir and no hot-reload.
//
// The checked-in dev default is empty, so a `quickshell -p shell` dev run and
// any host with no declared plugins behave exactly as before. shell.qml calls
// barWidgetComponent() to resolve a bar-layout id the first-party map did not
// claim; service/panel/overlay kinds are instantiated by shell.qml from the
// same list.
QtObject {
    id: root

    // Each entry: { id, name, version, kinds: [..], entryPoints: { kind: url } }
    // Regenerated by package.nix. Empty in the dev tree.
    readonly property var plugins: []

    // Component for a plugin bar-widget id, or null if no plugin claims it.
    // createComponent on an absolute file URL keeps this synchronous at first
    // use and cached thereafter.
    property var _cache: ({})
    function barWidgetComponent(id: string): Component {
        for (let i = 0; i < root.plugins.length; i++) {
            const p = root.plugins[i];
            if (p.id === id && p.entryPoints && p.entryPoints.barWidget) {
                if (!root._cache[id])
                    root._cache[id] = Qt.createComponent(p.entryPoints.barWidget);
                return root._cache[id];
            }
        }
        return null;
    }
}
