{
  imports = [
    ../generic/fontconfig.nix
    ../generic/shell.nix
    ../generic/git.nix
    ./_1password.nix
    ./git.nix
    ./shell.nix
    ./btop.nix
    ./fastfetch.nix
    ./ghostty.nix
    ./help.nix
    ./hypridle.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./kitty.nix
    ./locale.nix
    ./mako.nix
    ./waybar.nix
    ./wofi.nix
  ];
}
