{
  imports = [
    ../generic/fontconfig.nix
    ../generic/git.nix
    ../generic/shell.nix
    ../generic/packages.nix
    ../generic/theme.nix
    ./_1password.nix
    ./bat.nix
    ./btop.nix
    ./claude-code.nix
    ./fastfetch.nix
    ./fcitx5.nix
    ./fzf.nix
    ./keyboard.nix
    ./xournalpp.nix
    ./git.nix
    ./gtk.nix
    ./help.nix
    ./hypridle.nix
    ./hyprland.nix
    ./hyprlock.nix
    ./jylhis-theme.nix
    ./k9s.nix
    ./ghostty.nix
    ./lazygit.nix
    ./locale.nix
    ./noctalia.nix
    ./packages.nix
    ./screenshot.nix
    ./shell.nix
    ./waybar.nix
    ./vicinae.nix
    ./tracking

    ./xdg.nix
  ];
}
