import type { Command } from "commander";
import { type Runtime, usageError } from "@marchyo/core";

// Shell completions + man page, generated from the live commander tree so
// they can never drift from the actual surface. package.nix runs the
// compiled binary at build time to install the outputs.

export type CmdNode = {
  name: string;
  description: string;
  flags: string[];
  subs: CmdNode[];
};

export function extractTree(cmd: Command): CmdNode {
  return {
    name: cmd.name(),
    description: cmd.description(),
    flags: cmd.options.flatMap((o) => {
      const out: string[] = [];
      if (o.long) out.push(o.long);
      if (o.short) out.push(o.short);
      return out;
    }),
    subs: cmd.commands.map((c) => extractTree(c as Command)),
  };
}

const GLOBAL_FLAGS = [
  "--format",
  "--json",
  "--color",
  "--no-color",
  "--plain",
  "--no-animation",
  "--no-input",
  "--quiet",
  "--verbose",
  "--help",
  "--version",
];

export function fishCompletion(tree: CmdNode): string {
  const lines: string[] = [
    `# ${tree.name} fish completion — generated by \`${tree.name} completion fish\``,
  ];
  const esc = (s: string) => s.replace(/'/g, "\\'");
  for (const sub of tree.subs) {
    lines.push(
      `complete -c ${tree.name} -n '__fish_use_subcommand' -a '${sub.name}' -d '${esc(sub.description)}'`,
    );
    for (const nested of sub.subs) {
      lines.push(
        `complete -c ${tree.name} -n '__fish_seen_subcommand_from ${sub.name}' -a '${nested.name}' -d '${esc(nested.description)}'`,
      );
    }
    for (const flag of sub.flags.filter((f) => f.startsWith("--"))) {
      lines.push(
        `complete -c ${tree.name} -n '__fish_seen_subcommand_from ${sub.name}' -l ${flag.slice(2)}`,
      );
    }
  }
  for (const flag of GLOBAL_FLAGS.filter((f) => f.startsWith("--"))) {
    lines.push(`complete -c ${tree.name} -l ${flag.slice(2)}`);
  }
  return lines.join("\n") + "\n";
}

export function bashCompletion(tree: CmdNode): string {
  const top = tree.subs.map((s) => s.name).join(" ");
  const cases = tree.subs
    .filter((s) => s.subs.length > 0)
    .map(
      (s) =>
        `    ${s.name}) COMPREPLY=( $(compgen -W "${s.subs.map((n) => n.name).join(" ")}" -- "$cur") ); return ;;`,
    )
    .join("\n");
  return `# ${tree.name} bash completion — generated by \`${tree.name} completion bash\`
_${tree.name}() {
  local cur prev
  cur="\${COMP_WORDS[COMP_CWORD]}"
  prev="\${COMP_WORDS[1]}"
  if [ "$COMP_CWORD" -eq 1 ]; then
    COMPREPLY=( $(compgen -W "${top}" -- "$cur") )
    return
  fi
  case "$prev" in
${cases}
  esac
  COMPREPLY=( $(compgen -W "${GLOBAL_FLAGS.join(" ")}" -- "$cur") )
}
complete -F _${tree.name} ${tree.name}
`;
}

export function zshCompletion(tree: CmdNode): string {
  const subDescribe = tree.subs
    .map((s) => `    '${s.name}:${s.description.replace(/'/g, "")}'`)
    .join("\n");
  const cases = tree.subs
    .filter((s) => s.subs.length > 0)
    .map(
      (s) =>
        `        ${s.name}) _values '${s.name} subcommand' ${s.subs.map((n) => `'${n.name}[${n.description.replace(/[[\]']/g, "")}]'`).join(" ")} ;;`,
    )
    .join("\n");
  return `#compdef ${tree.name}
# generated by \`${tree.name} completion zsh\`
_${tree.name}() {
  local -a subcmds
  subcmds=(
${subDescribe}
  )
  if (( CURRENT == 2 )); then
    _describe 'command' subcmds
  else
    case "\${words[2]}" in
${cases}
        *) _default ;;
    esac
  fi
}
_${tree.name} "$@"
`;
}

export function manPage(tree: CmdNode, version: string): string {
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/-/g, "\\-");
  const sections = tree.subs
    .map((s) => {
      const subLines =
        s.subs.length > 0
          ? s.subs
              .map((n) => `.TP\n.B ${s.name} ${n.name}\n${esc(n.description)}`)
              .join("\n")
          : `.TP\n.B ${s.name}\n${esc(s.description)}`;
      return subLines;
    })
    .join("\n");
  return `.TH MARCHYO 1 "marchyo ${version}" "marchyo" "User Commands"
.SH NAME
marchyo \\- ${esc(tree.description)}
.SH SYNOPSIS
.B marchyo
[\\fIGLOBAL FLAGS\\fR] \\fICOMMAND\\fR [\\fIARGS\\fR]
.SH DESCRIPTION
The single control surface for a Marchyo desktop: runtime toggles and
theme switching (ephemeral, reset on activation), capture and session
helpers, and declarative system management through the marchyoCliState
sidecar. Mutating desktop commands follow the runtime\\-first contract:
live by default, \\fB\\-\\-apply\\fR to persist + rebuild, \\fB\\-\\-revert\\fR to undo.
.SH COMMANDS
${sections}
.SH GLOBAL FLAGS
${GLOBAL_FLAGS.map((f) => `.TP\n.B ${esc(f)}`).join("\n")}
.SH SEE ALSO
Full documentation: https://marchyo.org/docs/usage/cli/
`;
}

export async function runCompletion(
  rt: Runtime,
  program: Command,
  target: string,
  version: string,
): Promise<number> {
  const tree = extractTree(program);
  switch (target) {
    case "bash":
      process.stdout.write(bashCompletion(tree));
      return 0;
    case "zsh":
      process.stdout.write(zshCompletion(tree));
      return 0;
    case "fish":
      process.stdout.write(fishCompletion(tree));
      return 0;
    case "man":
      process.stdout.write(manPage(tree, version));
      return 0;
    default:
      return usageError(
        rt,
        `unknown completion target: "${target}"`,
        "marchyo completion <bash|zsh|fish|man>",
      );
  }
}
