name: Build Noctalia
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build Noctalia
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v15
        with:
          name: jylhis
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build Noctalia
        run: nix build .#noctalia
