name: Deploy docs
on:
  push:
    branches: [main]
    paths:
      - docs/**
      - flake.lock
      - flake.nix
      - outputs.nix
      - .github/workflows/pages.yml
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: pages
  cancel-in-progress: false
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
      - uses: cachix/cachix-action@v16
        with:
          name: jylhis
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
      - name: Build docs site
        run: nix build --accept-flake-config .#docs
      - uses: actions/upload-pages-artifact@v3
        with:
          path: result
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    timeout-minutes: 10
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
