# SOPS configuration for encrypting secrets
# Documentation: https://github.com/Mic92/sops-nix
# Creation rules define which keys are used to encrypt new/modified secrets
creation_rules:
  # Default rule for all secrets
  - path_regex: secrets/secrets\.yaml$
    age: >-
      age1example1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq, age1example2qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
  # Host-specific secrets (replace 'hostname' with actual host names)
  - path_regex: secrets/hosts/[^/]+\.yaml$
    age: >-
      age1example1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq
  # User-specific secrets
  - path_regex: secrets/users/[^/]+\.yaml$
    age: >-
      age1example1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq

# Notes:
# 1. Replace the example age keys above with your actual age public keys
# 2. Generate keys with: nix-shell -p age --run "age-keygen -o ~/.config/sops/age/keys.txt"
# 3. Get public key with: nix-shell -p age --run "age-keygen -y ~/.config/sops/age/keys.txt"
# 4. For NixOS hosts, generate keys with: nix-shell -p ssh-to-age --run "ssh-keyscan hostname | ssh-to-age"
# 5. Multiple keys can be listed (comma-separated) to allow multiple users/hosts to decrypt
